name: Create Release PR to Staging

on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure accurate branch comparison

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head: development    # Source branch
          base: staging        # Target branch
          title: "Release ${{ github.event.release.tag_name }}"
          body: "This PR merges `development` into `staging` for release `${{ github.event.release.tag_name }}`."
