name: Create Pull Request from Development to Staging

on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Release Branch
        run: |
          branch_name="release-${{ github.event.release.tag_name }}"
          target_commit="${{ github.event.release.target_commitish }}"

          # Ensure target commit exists; fallback to the branch if it doesn't
          if git rev-parse "$target_commit" >/dev/null 2>&1; then
            echo "Using target commit: $target_commit"
          else
            echo "Target commit $target_commit not found. Using the latest commit on branch: $target_commit"
            target_commit="origin/$target_commit"
          fi

          git checkout -b "$branch_name" "$target_commit"
          git push origin "$branch_name"

      - name: Create Pull Request on Behalf of User
        run: |
          branch_name="release-${{ github.event.release.tag_name }}"
          release_creator="${{ github.actor }}" # User who created the release

          gh pr create \
            --base staging \
            --head "$branch_name" \
            --title "Release ${{ github.event.release.tag_name }}: Merge $branch_name into staging" \
            --body "This pull request merges the release branch `$branch_name` into `staging` for release `${{ github.event.release.tag_name }}`.\n\nCreated by: @${release_creator}."
