name: Create Pull Request from Development to Staging

on:
  release:
    types:
      - published

permissions:
  contents: write        # Allows pushing commits, creating branches, etc.
  pull-requests: write   # Allows creating and modifying pull requests

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch All Branches and Tags
        run: git fetch --all

      - name: Create Release Branch
        run: |
          branch_name="release-${{ github.event.release.tag_name }}"
          target_commit="${{ github.event.release.target_commitish }}"
          branch="${{ github.event.release.target_commitish }}"
          
          # Check if target_commitish exists as a commit
          if git rev-parse "$target_commit" >/dev/null 2>&1; then
            echo "Using specified target commit: $target_commit"
          else
            echo "Target commit $target_commit does not exist. Using the latest commit on branch: $branch"
            target_commit="origin/$branch"
          fi

          git checkout -b "$branch_name" "$target_commit"
          git push origin "$branch_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          branch_name="release-${{ github.event.release.tag_name }}"
          gh pr create \
            --base staging \
            --head "$branch_name" \
            --title "Release ${{ github.event.release.tag_name }}: Merge $branch_name into staging" \
            --body "This pull request merges the release branch `$branch_name` into `staging` for release `${{ github.event.release.tag_name }}`."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
