name: Create Release PR from Development to Staging

on:
  release:
    types: [published]

permissions:
  contents: write        # Allows pushing commits, creating branches, etc.
  pull-requests: write  # Allows creating and modifying pull requests

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure accurate branch comparison

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging 
          base: development 
          title: "Release ${{ github.event.release.tag_name }}"
          body: "This PR merges `development` into `staging` for release `${{ github.event.release.tag_name }}`."
