name: Create Pull Request from Development to Staging

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

permissions:
  contents: write        # Allows pushing commits, creating branches, etc.
  pull-requests: write   # Allows creating and modifying pull requests

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to ensure accurate branch comparison

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
          base: staging
          commit-message: "Merge development into staging"
          title: "Development to Staging"
          body: |
            This pull request merges changes from `development` into `staging`.
