name: Create Pull Request from Development to Staging

on:
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write        # Allows pushing commits, creating branches, etc.
  pull-requests: write   # Allows creating and modifying pull requests

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          gh pr create \
            --base staging \
            --head development \
            --title 'Merge development into staging' \
            --body 'This pull request was created by a GitHub Action.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
